### ISSUE TITLE
Can't send quotation characters in message

### ISSUE THREAD

**Issue by virtser** [evanshortiss/sns-mobile#17] opened 2015-12-17 10:56 UTC
Try to send something like (notice the quotation marks in "these awesome"):

```
{
  "GCM":"{\"data\":{\"message\":\"Check out "these awesome" deals!\",\"url\":\"www.amazon.com\"}}"
}
```

And you will get the following error:
'Invalid parameter: Message Reason: Invalid notification for protocol GCM: Notification payload is malformed',

**Comment by evanshortiss** [comment] 2015-12-21 18:18
Hi @virtser,

That JSON doesn't look correctly escaped. I created an Object with the same content that when I call JSON.stringify on prints:

```javascript
var data = JSON.stringify(d= {GCM:{data:{message:'Check out "these awesome" deals!',url:'www.amazon.com'}}});

// Prints this
"{"GCM":{"data":{"message":"Check out \"these awesome\" deals!","url":"www.amazon.com"}}}"
```

**Comment by evanshortiss** [comment] 2015-12-21 18:22
@virtser let me know if verifying the format helps.

**Comment by virtser** [comment] 2015-12-22 07:20
@evanshortiss actually you can see in your readme file under publishToTopic section that you should escape the JSON with \", that's what SNS push infra expects. So the example that you gave won't work..

**Comment by evanshortiss** [comment] 2016-01-05 14:03
@virtser so you tried the format I provided and it failed? I didn't write the _publishToTopic_ section since I've not used topics so can't comment much about them unfortuantely. @abiskop might be of more help in that regard.

Perhaps this requires a patch in the conversion layer [here](https://github.com/evanshortiss/sns-mobile/blob/master/lib/interface.js#L635), or the internal quotes you've added around _these awesome_ need extra escaping. It calls _JSON.stringify_ for you but we'd need to test to see if that is the case.

My last suggestion would be to try the following, it has manually escaped the quotes you're having trouble with:
```
"GCM":"{\"data\":{\"message\":\"Check out \"these awesome\" deals!\",\"url\":\"www.amazon.com\"}}"
```

**Comment by virtser** [comment] 2016-01-05 15:18
@evanshortiss thanks Ivan, I tried escaping it myself of course. It didn't work obviously.

**Comment by abiskop** [comment] 2016-01-05 15:39
Hey folks, I think the problem is that the *default* key is missing in the dictionary. As stated in the Readme, this key is mandatory.

**Comment by abiskop** [comment] 2016-01-05 15:43
@virtser, could you please check what happens when you specify something for the *default* key?

**Comment by virtser** [comment] 2016-01-05 16:00
@abiskop it doesn't really make a difference to do it with or without default message, same result.
And it's not related to topics, I use this type of JSON message in sendMessage function.

**Comment by abiskop** [comment] 2016-01-05 17:44
@virtser, I'm on the road atm, but I will look into it the next days to see what's going on.

**Comment by evanshortiss** [comment] 2016-01-06 14:20
@virtser ok, it's odd, that it would claim the JSON I posted is malformed since it correctly parses. Check this image out

![JSON](https://dl.dropboxusercontent.com/u/58573547/Screen%20Shot%202016-01-06%20at%2009.16.26.png)

I may have to do with the _default_ key as @abiskop mentioned

**Comment by abiskop** [comment] 2016-02-09 18:04
@virtser @evanshortiss Okay folks, sorry for the delay. Just moved over to California from Germany which ate up quite a bit of my time...But it's awesome over here ;-)

I looked into the issue and found a solution I think. The issue probably is that you would have to insert a set of escaped backslashes before the (escaped) quotes, so that the backslashes will be preserved through the first layer of JSON deserialization:

``` js
> var o = { "GCM":"{\"data\":{\"message\":\"Check out \\\"these awesome\\\" deals!\",\"url\":\"www.amazon.com\"}}" }
undefined
> o
{ GCM: '{"data":{"message":"Check out \\"these awesome\\" deals!","url":"www.amazon.com"}}' }
> JSON.parse(o.GCM)
{ data: 
   { message: 'Check out "these awesome" deals!',
     url: 'www.amazon.com' } }
>
```

I didn't have a chance to test it on SNS, but I am pretty confident that this is the culprit (apart from the `default` key issue). @virtser Could you please check if this solves the issue?

**Comment by evanshortiss** [comment] 2016-02-09 20:15
Hi @virtser due to the replies by myself and @abiskop indicating this is a JSON String formatting issue I'll close this issue since it's not an issue with the module.

**Closed by evanshortiss** 2016-02-09 20:15 UTC

**Comment by virtser** [comment] 2016-02-10 12:25
That did the trick. 
Thanks a lot! :)
